title: Grav
default_lang: en
author:
  name: 'HD Stich'
  email: hd@two-on-a-journey.net
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
